version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:13
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    ports:
      - "5432:5432"
